Resolved 1 Error from CRAN "Additional issue"

I add a seed (`set.seed(22)`) in the offending example of `build_phytree_pq`. I tried to find the error using a loop, but after 50 different seed numbers, the examples still work on my side.